version: '3'

services:
    raza-matchs-ms:
        container_name: raza-matchs-ms
        build: .
        command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
        ports:
            - 8004:8000
        volumes:
            - .:/app
        env_file:
            - .env
        depends_on:
            raza-match-db:
                condition: service_healthy
        networks:
            - autenticador_network

    raza-match-db:
        image: postgres
        container_name: raza-match-db
        restart: always
        environment:
            - POSTGRES_USER=$RAZA_MATCH_DB_USER
            - POSTGRES_PASSWORD=$RAZA_MATCH_DB_PASSWORD
            - POSTGRES_DB=$RAZA_MATCH_DB_NAME
            - POSTGRES_HOST=raza_match
        ports:
            - $RAZA_MATCH_LOCAL_PORT:$RAZA_MATCH_DB_PORT_DOCKER
        networks:
            - autenticador_network
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "$RAZA_MATCH_DB_USER", "-d", "$RAZA_MATCH_DB_NAME" ]
            interval: 15s
            timeout: 15s
            retries: 15

networks:
    autenticador_network:
        external: true
